In [ ]:
import os
import re
from importlib import metadata
import numpy as np
import tiktoken
import matplotlib.pyplot as plt
import urllib.request
import torch 
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader

In [3]:
file_path = "the-verdict.txt"

if not os.path.exists(file_path):
    url = (
        "https://raw.githubusercontent.com/rasbt/"
        "LLMs-from-scratch/main/ch02/01_main-chapter-code/"
        "the-verdict.txt"
    )
    with urllib.request.urlopen(url, timeout=30) as response, open(
        file_path, "wb"
    ) as file_handle:
        file_handle.write(response.read())

with open(file_path, "r", encoding="utf-8") as f:
    raw_text = f.read()
#print("Total Number of chars in the book: ", len(raw_text))
#print(raw_text[:99])

preprocessed =  re.split(r'([,.:;?_!"()\']|--|\s)', raw_text)
preprocessed = [item.strip() for item in preprocessed if item.strip()]
#print(preprocessed[:30])

all_words = sorted(set(preprocessed))
vocab_size = len(all_words)
vocab = {token: integer for integer, token in enumerate(all_words)}

for i, item in enumerate(vocab.items()):
    #print(item)
    if i >= 50:
        break


In [4]:
tokenizer = tiktoken.get_encoding("gpt2")
enc_text = tokenizer.encode(raw_text)
enc_sample = enc_text[50:]
context_size = 4

#text = """"the last he painted, you know, """
#ids = tokenizer.encode(text)
#decoded = tokenizer.decode(ids)

X = enc_text[:context_size]
y = enc_text[:context_size+1]

#print(f"x: {X}")
#print(f"y:      {y}")
for i in range(1, context_size+1):
    context = enc_sample[:i]
    desired = enc_sample[i]
    print(context, "---->", desired)
    print(tokenizer.decode(context), "---->", tokenizer.decode([desired]))


[290] ----> 4920
 and ---->  established
[290, 4920] ----> 2241
 and established ---->  himself
[290, 4920, 2241] ----> 287
 and established himself ---->  in
[290, 4920, 2241, 287] ----> 257
 and established himself in ---->  a


In [5]:
class GPTDatasetV1(Dataset):
    def __init__(self, txt, tokenizer, max_length, stride):
        self.input_ids = []
        self.target_ids = []

        # Tokenize the entire text
        token_ids = tokenizer.encode(txt, allowed_special={"<|endoftext|>"})
        assert len(token_ids) > max_length, "Number of tokenized inputs must at least be equal to max_length+1"

        # Use a sliding window to chunk the book into overlapping sequences of max_length
        for i in range(0, len(token_ids) - max_length, stride):
            input_chunk = token_ids[i:i + max_length]
            target_chunk = token_ids[i + 1: i + max_length + 1]
            self.input_ids.append(torch.tensor(input_chunk))
            self.target_ids.append(torch.tensor(target_chunk))

    def __len__(self):
        return len(self.input_ids)

    def __getitem__(self, idx):
        return self.input_ids[idx], self.target_ids[idx]


def create_dataloader_v1(txt, batch_size=4, max_length=256,
                         stride=128, shuffle=True, drop_last=True,
                         num_workers=0):

    # Initialize the tokenizer
    tokenizer = tiktoken.get_encoding("gpt2")

    # Create dataset
    dataset = GPTDatasetV1(txt, tokenizer, max_length, stride)

    # Create dataloader
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        drop_last=drop_last,
        num_workers=num_workers
    )

    return dataloader

dataloader = create_dataloader_v1(raw_text, batch_size=8, max_length=4, stride=4, shuffle=False)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)

print("Inputs:\n", inputs)
print("\nTargets:\n", targets)

# Decode each sequence in the batch (tiktoken.decode expects a list of ints, not a tensor)
#for i in range(len(inputs)):
    #decoded = tokenizer.decode(inputs[i].tolist())
    #print("----", decoded)
   

Inputs:
 tensor([[   40,   367,  2885,  1464],
        [ 1807,  3619,   402,   271],
        [10899,  2138,   257,  7026],
        [15632,   438,  2016,   257],
        [  922,  5891,  1576,   438],
        [  568,   340,   373,   645],
        [ 1049,  5975,   284,   502],
        [  284,  3285,   326,    11]])

Targets:
 tensor([[  367,  2885,  1464,  1807],
        [ 3619,   402,   271, 10899],
        [ 2138,   257,  7026, 15632],
        [  438,  2016,   257,   922],
        [ 5891,  1576,   438,   568],
        [  340,   373,   645,  1049],
        [ 5975,   284,   502,   284],
        [ 3285,   326,    11,   287]])


In [6]:
vocab_size = 50257
output_dim = 256

token_embedding_layer = torch.nn.Embedding(vocab_size, output_dim)

max_length = 4
dataloader = create_dataloader_v1(
    raw_text, batch_size=8, max_length=max_length,
    stride=max_length, shuffle=False
)

data_iter = iter(dataloader)
inputs, targets = next(data_iter)

#print("Inputs:\n", inputs)
#print("\nTargets:\n", targets)

token_embeddings = token_embedding_layer(inputs)
context_length = max_length

pos_embedding_layer = torch.nn.Embedding(context_length, output_dim)
#print(pos_embedding_layer.weight)
pos_embeddings = pos_embedding_layer(torch.arange(max_length))

# Combine the both embeddings
input_embeddings = token_embeddings + pos_embeddings

# First vector (first token, first batch): show individually then merged
# print(token_embeddings[0, 0, :])
# print(pos_embeddings[0, :])
# print(input_embeddings[0, 0, :])





# Self Attention walk through  with 1 token (2)


In [7]:
# Self Attention walk through  with 1 token (2)

inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)
# Step 1 - Attention Scores
query_idx = 1
query = inputs[query_idx] #2nd input token is the query (Journey)
# print(query)
attn_scores_2 = torch.empty(inputs.shape[0])
for i, x_i in enumerate(inputs):
    attn_scores_2[i] = torch.dot(x_i, query) #dot product (transpose not necessary here since they are 1-dim vectors)
    #print(x_i,query)
print("Step 1 - Attention Scores", attn_scores_2)

# Step 2 - Attention weights (Normalise with softmax (torch) attention weights)
attn_weights_2 = torch.softmax(attn_scores_2, dim=0)
print("Step 2 - Attention Weights", attn_weights_2 * 100)

context_vec_2 = torch.zeros(query.shape)
for i,x_i in enumerate(inputs):
    #print(attn_weights_2[i], "*", x_i)
    context_vec_2 += attn_weights_2[i]*x_i

print("Step 3 - Context Vector", context_vec_2)



Step 1 - Attention Scores tensor([0.9544, 1.4950, 1.4754, 0.8434, 0.7070, 1.0865])
Step 2 - Attention Weights tensor([13.8548, 23.7891, 23.3274, 12.3992, 10.8182, 15.8114])
Step 3 - Context Vector tensor([0.4419, 0.6515, 0.5683])


# Self Attention walk through all tokens

In [8]:
# Calcualte Self Attention easy way with all tokens
attn_scores = torch.empty(6, 6)

for i, x_i in enumerate(inputs):
    #print(x_i)
    for j, x_j in enumerate(inputs):
       attn_scores[i, j] = torch.dot(x_i, x_j)
       #print("--", attn_scores[i, j])
#print("Loop",attn_scores)

# Step 1 - Attention Scores (easy eway)
attn_scores = inputs @ inputs.T
#print(attn_scores)

# Step 2 - Normalise with softmax (torch) attention weights
attn_weights = torch.softmax(attn_scores, dim=1)
#print(attn_weights)

#sum_them = sum(attn_weights[1])
#print(sum_them)

# Step 3 - Context Vector
context_vec = attn_weights @ inputs
#print(context_vec)


In [9]:
# Self Attention with trainable weights 1 query (Journey) (2) scaled dot product

inputs = torch.tensor(
  [[0.43, 0.15, 0.89], # Your     (x^1)
   [0.55, 0.87, 0.66], # journey  (x^2)
   [0.57, 0.85, 0.64], # starts   (x^3)
   [0.22, 0.58, 0.33], # with     (x^4)
   [0.77, 0.25, 0.10], # one      (x^5)
   [0.05, 0.80, 0.55]] # step     (x^6)
)

the_main_query = 1

x_2 = inputs[the_main_query]
d_in = inputs.shape[1] # the input embedding size, d=3
d_out = 2 # the output embedding size, d=2


torch.manual_seed(123)

W_query = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_key   = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)
W_value = torch.nn.Parameter(torch.rand(d_in, d_out), requires_grad=False)


query_2 = x_2 @ W_query
key_2   = x_2 @ W_key
value_2 = x_2 @ W_value

# All tokens
keys = inputs @ W_key
values = inputs @ W_value


keys_2 = keys[1]
attn_score_22 = query_2 @ keys.T
print(attn_score_22)

d_k = keys.shape[-1]
attn_weights_2 = torch.softmax(attn_score_22 / d_k**0.5, dim=-1)
print(attn_weights_2)

context_vector =  attn_weights_2 @ values
print(context_vector)





tensor([1.2705, 1.8524, 1.8111, 1.0795, 0.5577, 1.5440])
tensor([0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820])
tensor([0.3061, 0.8210])


In [14]:
class SelfAttention_v1(nn.Module):

    def __init__(self, d_in, d_out):
        super().__init__()
        self.W_query = nn.Parameter(torch.rand(d_in, d_out))
        self.W_key   = nn.Parameter(torch.rand(d_in, d_out))
        self.W_value = nn.Parameter(torch.rand(d_in, d_out))

    def forward(self, x):
       #print(x)
       queries = x @ self.W_query
       keys = x @ self.W_key
       values = x @ self.W_value

       attn_scores = queries @ keys.T # omega
       attn_weights = torch.softmax(
            attn_scores / keys.shape[-1]**0.5, dim=-1
        )

       context_vec = attn_weights @ values

       #print("queries",queries)
       #print("keys",keys)
       #print("Values",context_vec)

       return attn_weights

torch.manual_seed(123)
sa_v1 = SelfAttention_v1(d_in, d_out)
print(sa_v1(inputs))

tensor([[0.1551, 0.2104, 0.2059, 0.1413, 0.1074, 0.1799],
        [0.1500, 0.2264, 0.2199, 0.1311, 0.0906, 0.1820],
        [0.1503, 0.2256, 0.2192, 0.1315, 0.0914, 0.1819],
        [0.1591, 0.1994, 0.1962, 0.1477, 0.1206, 0.1769],
        [0.1610, 0.1949, 0.1923, 0.1501, 0.1265, 0.1752],
        [0.1557, 0.2092, 0.2048, 0.1419, 0.1089, 0.1794]],
       grad_fn=<SoftmaxBackward0>)


In [34]:
class SelfAttention_v2(nn.Module):

    def __init__(self, d_in, d_out, qkv_bias=False):
        super().__init__()
        self.W_query = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_key   = nn.Linear(d_in, d_out, bias=qkv_bias)
        self.W_value = nn.Linear(d_in, d_out, bias=qkv_bias)

    def forward(self, x):
        #print("x",x)
        keys = self.W_key(x)
        queries = self.W_query(x)
        values = self.W_value(x)

        attn_scores = queries @ keys.T
        attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)
        context_vec = attn_weights @ values

        return context_vec

torch.manual_seed(789)
sa_v2 = SelfAttention_v2(d_in, d_out)
print(sa_v2(inputs))

tensor([[-0.0739,  0.0713],
        [-0.0748,  0.0703],
        [-0.0749,  0.0702],
        [-0.0760,  0.0685],
        [-0.0763,  0.0679],
        [-0.0754,  0.0693]], grad_fn=<MmBackward0>)


In [45]:
queries = sa_v2.W_query(inputs)
keys = sa_v2.W_key(inputs)
values = sa_v2.W_value(inputs)

attn_scores = queries @ keys.T
attn_weights = torch.softmax(attn_scores / keys.shape[-1]**0.5, dim=-1)
context_vec = attn_weights @ values

print(attn_scores.shape[0])

context_length = attn_scores.shape[0]
mask_simple = torch.tril(torch.ones(context_length, context_length))
print(mask_simple)





6
tensor([[1., 0., 0., 0., 0., 0.],
        [1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0.],
        [1., 1., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1.]])
